version: "3.8"

services:
  kelmith-web-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - ./.env
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= 90rtfol10
      - POSTGRES_DB= essays
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
